### DISCUSSION TITLE
Network/firewall

### DISCUSSION THREAD

**Discussion by Ali-Meh** [pactus-project/pactus#101] [Ideas]
# Pactus Peer Firewall 
---

### What problem are you trying to solve?
* _A node wants to listen to whitelisted peers Only or trying to blacklist some peers_
* _Config sub command to whitelist or blacklist peers and save them to a persistent store reusable for future detector algorithm_

### How do you propose to solve it?
* _Add whitelist and blacklist sub-commands to Config command of CLI to add or remove peers._
* _Don't connect to blacklisted peers and if already connected drop it via [this ability](https://github.com/libp2p/go-libp2p-daemon/issues/22#issuecomment-439303471)_
* _Check to not connect to these peers or only connect to whitelist peers here._
* _Implement Check on connectivity Check of [bootstrap goroutine](https://github.com/zarbchain/zarb-go/blob/main/network/bootstrap.go#L130)._

### What other approaches did you consider?
* _could just ignore the message published from these peers but it's resource intensive so i say just drop peer._

### Proposed structs to add to network/firewall
```go
// BootstrapConfig holds all configuration options related to bootstrap nodes
type BootstrapConfig struct {
	// Peers to connect to if we fall below the threshold.
	Addresses []string
	// MinPeerThreshold is the number of connections it attempts to maintain.
	MinThreshold int
	// MaxThreshold is the threshold of maximum number of connections.
	MaxThreshold int
	// Period is the interval at which it periodically checks to see
	// if the threshold is maintained.
	Period time.Duration
	// ConnectionTimeout is how long to wait before timing out a connection attempt.
	Timeout time.Duration
	//PeerFilters keeps track of whitelisted or blacklisted peers
	PeerFilters *PeerFilter
}

//PeerFilter has the list of peers to whitelist and a list to blacklist so never connect to blacklist and if set only whitelist
//flag is set then only allow whitelisted peers to connect
type PeerFilter struct {
	WhiteListedPeers []peer.AddrInfo
	BlackListedPeers []peer.AddrInfo
	OnlyWhiteList    bool
}

//PeerSelector is the func interface needs to be passed before starting to connect to the
//newly identified peers
type PeerSelector interface {
	//check to see if Peer is allowed to connect
	CanConnect(peer.ID) bool
	//Blacklist(true) adds /(false) will drop peer to/from Blacklisted peers list
	Blacklist(peer.ID, bool) error
	//Whitelist(true) adds /(false) will drop peer to/from whitelisted peers list
	Whitelist(peer.ID, bool) error
	//SetOnlyWhiteList will set PeerFilter.OnlyWhiteList
	SetOnlyWhiteList(bool) error
}
```

### What could go wrong?
* _May need to save IpAddress of the peer on blacklist subcommand  for future use!_
* _Might be better to expose a channel to notifie PeerSelector of newly [detected badPeer](https://github.com/zarbchain/zarb-go/blob/main/sync/firewall/firewall.go#L54) to blacklist but this way only needs to pass the network object to [sync/firewall](https://github.com/zarbchain/zarb-go/blob/main/sync/sync.go#L74)_
--- 
@b00f @nagarajmanjunath

**Comment by Ali-Meh** [comment]
the initial test with this approach suggests gonna need better persistence method as toml config file might get so big 

```toml
[State]
  MintbaseAddress = ""
  [State.Store]
    Path = "data"

[TxPool]
  WaitingTimeout = 2000000000
  MaxSize = 2000

[Consensus]
  TimeoutPrepare = 3000000000
  TimeoutPrecommit = 2000000000
  DeltaDuration = 1000000000

[Network]
  Name = "zarb"
  Address = "/ip4/0.0.0.0/tcp/0"
  NodeKeyFile = "node_key"
  EnableMDNS = true
  EnableKademlia = true
  [Network.Bootstrap]
    Addresses = []
    MinThreshold = 8
    MaxThreshold = 16
    Period = 60000000000
    Timeout = 20000000000
-----------------------------------------------------------------------------------------------
    [Network.Bootstrap.PeerFilters]
      OnlyWhiteList = true

      [[Network.Bootstrap.PeerFilters.WhiteListedPeers]]
        ID = "12D3KooWNYD4bB82YZRXv6oNyYPwc5ozabx2epv75ATV3D8VD3Mq"

        [[Network.Bootstrap.PeerFilters.WhiteListedPeers.Addrs]]
-----------------------------------------------------------------------------------------------
[Logger]
  Colorfull = true
  [Logger.Levels]
    _capnp = "error"
    _consensus = "info"
    _grpc = "error"
    _http = "error"
    _network = "error"
    _pool = "error"
    _state = "info"
    _sync = "warning"
    default = "info"

[Sync]
  Moniker = ""
  StartingTimeout = 5000000000
  HeartBeatTimeout = 5000000000
  SessionTimeout = 3000000000
  InitialBlockDownload = true
  BlockPerMessage = 10
  CacheSize = 100000

[Capnp]
  Enable = true
  Address = "[::]:37621"

[Http]
  Enable = true
  Address = "[::]:8081"

[GRPC]
  Enable = true
  Address = "[::]:9090"
  [GRPC.Gateway]
    Enable = true
    Address = "[::]:8080"

```
