### ISSUE TITLE
Reachability shows as Private

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1539]
Some public nodes shows the Reachability as Private (that should be incorrect)

**Comment by Ja7ad** [comment]
> Some public nodes shows the Reachability as Private (that should be incorrect)

@b00f I debug network with this configuration:

```toml
  public_addr = ""
  listen_addrs = []
  bootstrap_addrs = []
  max_connections = 300
  enable_udp = true
  enable_nat_service = true
  enable_upnp = false
  enable_relay = false
  enable_relay_service = true
  enable_mdns = false
  enable_metrics = false
  force_private_network = false
```

But give `private` event from network.

![Screenshot From 2024-10-13 12-02-40](https://github.com/user-attachments/assets/025ab43b-efad-4d4a-9313-22d532e377b2)
