### ISSUE TITLE
Add configuration for the consumption fee

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1541]
All parameters for calculating the fee are configurable. However, we recommend the following configurations:

For most validators, we suggest setting the unit price to 0 PAC and the fixed fee to 0.01 PAC. This configuration eliminates the consumption fee, meaning these validators will only apply the fixed fee.

For validators with good resources, we recommend setting the daily limit to 280 bytes, the unit price to 0.000005 PAC, and the fixed fee to 0 PAC. This allows users to send almost up to 5 free or low-fee transactions, but they will need to wait for these validators to enter the committee and propose the block. This way, the Pactus blockchain can support zero-fee transactions.

https://pips.pactus.org/PIPs/pip-31#:~:text=their%20preferred%20value.-,Configuration,-All%20parameters%20for

## Example config

```toml
# `tx_pool` contains configuration options for the transaction pool module.
[tx_pool]

  # `max_size` indicates the maximum number of unconfirmed transactions inside the pool.
  # Default is `1000`.
  max_size = 1000

  [tx_pool.fee]
    daily_limit = 280
    unit_price = 0.000005
    fixed_fee = 0.01
```

https://github.com/pactus-project/pactus/blob/2bcb8d60be6bef68509658dd71d967fce61d1090/config/example_config.toml#L122-L124

## Basic check

- `daily_limit` don't allowing zero value.
